services:
  # Application service
  web:
    build:
      context: .
      args:
        requirements_file: ./requirements.txt
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./data:/data
    depends_on:
      - mongodb
    env_file: .env
    restart: always
    networks:
      - app-network

  # MongoDB Database
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: fantasy_library
    volumes:
      - mongo_data:/data/db
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
